-- [문제 푼 날짜]
-- 1. 5월 3일 (O) 5분 1초 OK



SELECT
    B.USER_ID,
    B.NICKNAME,
    SUM(A.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD AS A
INNER JOIN
    USED_GOODS_USER AS B
    ON A.WRITER_ID = B.USER_ID
WHERE
    A.STATUS = 'DONE'
GROUP BY
    B.USER_ID,
    B.NICKNAME
HAVING
    SUM(A.PRICE) >= 700000
ORDER BY
    TOTAL_SALES ASC;
    