-- [문제 푼 날짜]
-- 1. 3월 31일 (X) 
-- 2. 4월 1일 ()


SELECT
    B.CATEGORY,
    SUM(A.SALES) AS TOTAL_SALES
FROM
    BOOK_SALES AS A
INNER JOIN
    BOOK AS B
    ON A.BOOK_ID = B.BOOK_ID
WHERE
    A.SALES_DATE >= '2022-01-01'
    AND A.SALES_DATE < '2022-02-01'
GROUP BY
    B.CATEGORY
ORDER BY
    B.CATEGORY ASC;